#!/usr/bin/env bash

device=$(bluetoothctl devices | awk {'print $3'} | rofi -dmenu -p Bluetooth)
mac=$(bluetoothctl devices | grep $device | awk {'print $2'} )
if [[ -z "$mac" ]]; then
  exit 0
fi
connected=$(bluetoothctl devices Connected | grep $mac)
if [[ -z "$connected" ]]; then
  bluetoothctl connect $mac || notify-send "Connection failed"
else
  bluetoothctl disconnect $mac 
fi
