#!/usr/bin/env bash

function list_geometry () {
	[ "$2" = with_description ] && local title="\t\(.title)" || local title=
    if [ "$1" = focused ]; then
      echo $(hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])'$title'"')
    fi
}

FOCUSED=`list_geometry focused`

CHOICE=`rofi -dmenu -p 'Screenshot' << EOF
fullscreen
region
focused
EOF`

FILENAME="$(date +'%Y-%m-%d-%H%M%S_screenshot.png')"
EXPENDED_FILENAME="/home/$USER/Pictures/screenshot/$FILENAME"

if [[ $CHOICE == "fullscreen" ]]; then
  grim $EXPENDED_FILENAME
elif [[ $CHOICE == "region" ]]; then
  grim -g "$(slurp)" $EXPENDED_FILENAME
elif [[ $CHOICE == "focused" ]]; then
  grim -g "$FOCUSED" $EXPENDED_FILENAME
elif [[ $CHOICE == "" ]]; then
  notify-send "Screenshot" "Cancelled"
  exit 0
fi


if command -v swappy $>/dev/null
then
    EDIT_CHOICE=`rofi -dmenu -p 'Edit' -lines 2 << EOF
yes
no
EOF`
    if [[ $EDIT_CHOICE == "yes" ]]; then
      swappy -f "$EXPENDED_FILENAME" -o "$EXPENDED_FILENAME"
    fi
fi

notify-send "Screenshot" "File saved as <i>'$FILENAME'" -i $EXPENDED_FILENAME
