#!/usr/bin/env bash

# ----------------------------------------------------- 
# Select random wallpaper and create color scheme
# ----------------------------------------------------- 

wal=$(find "$HOME/wallpapers/" -maxdepth 1 -type f | shuf -n 1)
theme-and-wallpaper $wal
