#!/usr/bin/env bash

# ----------------------------------------------------- 
# Select wallpaper and create color scheme
# ----------------------------------------------------- 
wal=$(ls ~/wallpapers | rofi -dmenu -i -p Wallpaper )
wal -q -i ~/wallpapers/$wal

# ----------------------------------------------------- 
# Load current pywal color scheme
# ----------------------------------------------------- 
source "$HOME/.cache/wal/colors.sh"

# ----------------------------------------------------- 
# Copy color file to waybar folder
# ----------------------------------------------------- 
cp ~/.cache/wal/colors-waybar.css ~/.config/waybar/

# ----------------------------------------------------- 
# get wallpaper image name
# ----------------------------------------------------- 
newwall=$(echo $wallpaper | sed "s|$HOME/wallpapers/||g")

# ----------------------------------------------------- 
# Set the new wallpaper
# ----------------------------------------------------- 
swww img $wallpaper --transition-step 20 --transition-fps=20
killall waybar
waybar &

extension="${wallpaper##*.}"
rm -rf ~/.config/current-wallpaper.*
cp $wallpaper ~/.config/current-wallpaper.$extension

# ----------------------------------------------------- 
# Send notification
# ----------------------------------------------------- 
notify-send "Theme and Wallpaper updated" "With image $newwall"

echo "DONE!"
