#!/usr/bin/env bash

# ----------------------------------------------------- 
# Select wallpaper and create color scheme
# ----------------------------------------------------- 

wal=$(ls ~/wallpapers | rofi -dmenu -i -p Wallpaper )
if [[ $wal == "" ]]; then
  notify-send "Theme and Wallpaper" "Not changed"
  exit 1
fi
~/scripts/theme-and-wallpaper "$HOME/wallpapers/$wal"
